export const MSG = {
  SHOW_OVERLAY: 'SHOW_OVERLAY',
  HIDE_OVERLAY: 'HIDE_OVERLAY',
  INSERT_TEXT: 'INSERT_TEXT',

  OVERLAY_READY: 'OVERLAY_READY',
  RETRY_DICTATION: 'RETRY_DICTATION',
  DISMISS_OVERLAY: 'DISMISS_OVERLAY',
  STOP_DICTATION: 'STOP_DICTATION',
  START_DICTATION: 'START_DICTATION',
  GET_SHORTCUT_LABEL: 'GET_SHORTCUT_LABEL',

  OFFSCREEN_READY: 'OFFSCREEN_READY',
  START_RECORDING: 'START_RECORDING',
  STOP_RECORDING: 'STOP_RECORDING',

  RECORDING_READY: 'RECORDING_READY',
  AUDIO_CHUNK: 'AUDIO_CHUNK',
  RECORDING_STOPPED: 'RECORDING_STOPPED',
  OFFSCREEN_ERROR: 'OFFSCREEN_ERROR',

  GET_SETTINGS: 'GET_SETTINGS',
  SAVE_SETTINGS: 'SAVE_SETTINGS',
  GET_HISTORY: 'GET_HISTORY',
  DELETE_HISTORY_ITEM: 'DELETE_HISTORY_ITEM',
  CLEAR_HISTORY: 'CLEAR_HISTORY',
  COPY_TEXT: 'COPY_TEXT',
  INJECT_CONTENT_SCRIPT: 'INJECT_CONTENT_SCRIPT',
};

export const STORAGE_KEYS = {
  API_KEY: 'typestream_api_key',
  HOTKEY_PREFERENCE: 'hotkey_preference',
  HISTORY: 'history',
  SETTINGS: 'settings',
};

export const API = {
  BASE: 'https://api.typestream.dev',
  ENDPOINTS: {
    CREATE_SESSION: '/sessions',
    COMPLETE: (id) => `/sessions/${id}/complete`,
    TRANSCRIBE: '/transcribe',
  },
};

export const OVERLAY_STATES = {
  LISTENING: 'listening',
  PROCESSING: 'processing',
  RESOLUTION: 'resolution',
  ERROR: 'error',
};

export const DEFAULT_SETTINGS = {
  saveHistory: true,
  autoCopy: true,
  playSounds: false,
  showFloatingBar: false,
};

export const MAX_HISTORY = 200;
